# Generated by Django 2.1.3 on 2018-11-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturantapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
    ]
